# Site settings
baseurl = "https://yzzilk.github.io/liz_biz/"
languageCode = "en-us"
title = "Revwoo"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-91186708-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Revwoo Inc."
  description = "Revwoo is an online marketplace helping small business entrepreneurs find accountants and accounting resources in the Seattle area."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.revwoo.com"
  #  ID = "42"
  #  # Track all subdomains with "*.revwoo.com"
  #  domain = "www.revwoo.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Revwoo Inc."
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Services"
    portfolio = "Portfolio"
    about = "About"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://jljoylularoe.thinkific.com/"
      name = "Courses"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = " "
    subtitle = "Accounting Marketplace"
    buttonText = "Tell me more"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = "Revwoo is an online marketplace helping small business entrepreneurs find accountants and accounting resources in the Seattle area."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-comments"
      title = "Advice"
      description = "Need expert accounting advice? Connect with an accountant via Revwoo."
      url = "#contact"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Accountant Referral"
      description = "Revwoo will connect you with an experienced and quality-vetted accountant aligned with your business need."
      url = "#contact"

    [[params.services.row.list]]
      icon = "fa-video-camera"
      title = "Courses"
      description = "Revwoo provides industry specific accounting and business training courses to help entrepreneurs get started."
      url = "http://jljoylularoe.thinkific.com/"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "Our journey as accounting service matchmakers."
    endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "March 2016"
      title = "Idea"
      description = "Accountants are in high demand, yet we see a trend in people leaving the profession. Oftentimes, this trend affects women who are seeking more location and schedule flexibility. We set out on a mission to connect people in need of accounting services with freelance accountants helping fill a gap on both sides of the marketplace equation."

    [[params.about.events]]
      img = "2.jpg"
      date = "April 2016"
      title = "Formation"
      description = "Revwoo Inc. is formed with the goal of matching entrepreneurs with quality-vetted freelance accountants serving the Seattle area."

    [[params.about.events]]
      img = "3.jpg"
      date = "July 2016"
      title = "Customer Base Focus"
      description = "In order to better serve our customers, we decided to focus our marketing efforts on a more specific customer base."

    [[params.about.events]]
      img = "4.jpg"
      date = "September 2016"
      title = "Online Courses"
      description = "After six months of seeing the challenges and questions entrepreneurs had, we decided to address the most common questions for specific industries through online courses. This enables us to help more entrepreneurs and more efficiently meet the needs of our customers. We started out with content specific to LuLaRoe Consultants since we saw strong demand from this growing business."


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Team"
    subtitle = "Behind the matchmaking."
    description = "We are commited and obsessed with making small business entrepreneurs lives easier on the accounting front."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Liz Koser Thurston"
      position = "Founder & CEO"
      
      livesIn = "[Seattle, WA](https://www.google.com/maps/place/Seattle,+WA)"
      
        
        
      
    
	  
      social = [
        ["fa-twitter", "https://twitter.com/Busy_Liz_Biz"],
        
        ["fa-linkedin", "https://www.linkedin.com/in/lizkoser"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Brian Bass"
      position = "Co-founder & COO"
	  livesIn = "[Seattle, WA](https://www.google.com/maps/place/Seattle,+WA)"
      social = [

	  
        ["fa-linkedin", "https://www.linkedin.com/in/brian-bass-cpa-562b416"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Jessica Ruppert"
      position = "Co-founder & CTO"
	  livesIn = "[Reno, NV](https://www.google.com/maps/place/Reno,+NV)"		  
      social = [
        ["fa-twitter", "https://twitter.com/jesslooroo"],
   
        ["fa-linkedin", "https://www.linkedin.com/in/jessicaruppert"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "We would love to hear from you."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "info@revwoo.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for contacting us. We will get back to you within 24 business hours."
    #error = "Message could not be send. Please contact us at info@revwoo.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Copyright Â© Revwoo Inc. 2017"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/RevwooAcct"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/revwoo/"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "https://www.linkedin.com/company/revwoo-inc."

    [[params.footer.quicklinks]]
      text = " "
      link = "#"

    [[params.footer.quicklinks]]
      text = " "
      link = "#"
